### ISSUE TITLE
Review posted on behalf of Dr Alexandre Franco

### ISSUE THREAD

**Issue by lunebellec** [Brainhack-Proceedings-2015/ITO-AMX-LI#1]
Well written paper showing on the applicability of calculating the laterality index in fsl. The script is also available in the group’s website. 

Just some very minor comments:

Could include an extra comment on why 3 out of the 4 subjects showed left lateralized activation. Especially on the subject that has a cortical left-hemisphere stroke (mean LI = 0.96, left lateralized). Showing the activation maps in the 4 images shown on figure 1 would possible help with the argument. 

Looks like there is an error in reference [1]

**Comment by npnl** [comment]
Thank you for your kind comments and suggestions. We have responded to them here:

• Could include an extra comment on why 3 out of the 4 subjects showed left lateralized activation. Especially on the subject that has a cortical left-hemisphere stroke (mean LI = 0.96, left lateralized).

 We appreciate the reviewer's suggestion. In fact, this laterality index calculation was part of a larger study in which we examined the laterality of the action observation network across individuals with left vs right hemisphere stroke. We have now added in the results the following (https://github.com/npnl/LI-FSL/blob/master/LI_Abstract/Ito-Brainhack-LA-report.pdf )

"These LI results corresponded with our whole brain observations (not included here), in which we examined the laterality of the action observation network in individuals with left versus right hemisphere stroke (Ito, OHBM 2016). Briefly, we show that most individuals show a left-lateralized pattern of activity during action observation, regardless of the lesion location. That is, both individuals with left-hemisphere stroke and right-hemisphere stroke tend to activate the left, dominant hemisphere, suggesting a role of hemispheric dominance during recovery after stroke." 

• Showing the activation maps in the 4 images shown on figure 1 would possibly help with the argument.

We thank the reviewer for this great suggestion and have added a figure 2, which can be seen n the pdf version (https://github.com/npnl/LI-FSL/blob/master/LI_Abstract/Ito-Brainhack-LA-report.pdf ). We have also added in an extra script (2_ROI_ActivationMap.sh; https://github.com/npnl/LI-FSL/tree/master/LateralityIndex_20160401 ) that will help users in visualizing the activity within the region of interest.

• Looks like there is an error in reference [1]

We thank the Reviewer for pointing this out. We've updated the correct reference to:  

Jansen, A., Menke, R., Sommer, J., Förster, A. F., Bruchmann, S., Hempleman, J., ... & Knecht, S. (2006). The assessment of hemispheric lateralization in functional MRI—robustness and reproducibility. Neuroimage, 33(1), 204-217.

**Comment by lunebellec** [comment]
@npnl it looks like you addressed all issues. Please close the issue if this is the case. I will contact Dr Franco for him to double check your responses. Best,

Pierre

**Comment by engfranco** [comment]
@npnl, yes, all my concerns in regards to the abstract have been addressed. 
Best, 
Alex

**Comment by lunebellec** [comment]
OK so both issues have been addressed. Consider the abstract accepted. I will get back to you when we move into production with gigascience. Congratulations!
